### ISSUE TITLE
trying to install Nuget OpenTrans.net package with Visual Code on Linux

### ISSUE THREAD

**Issue by zdavatz** [stephanstapel/OpenTrans.net#7]
I am trying to install the latest Nuget package and I constantly get the following error:

![latest-screenshot](https://user-images.githubusercontent.com/4953/82598272-af89a300-9baa-11ea-8f20-9af30013dbc9.png)

Steps to reproduce are:
1. Open VSCode on Linux
2. Press `Control+Shift+P`
3. Enter `Nuget Package Manager: Add Package`
4. Search for `Opentrans`
5. Select correct version.
6. Above error happens.

**Comment by stephanstapel** [comment]
Hi,
I have no experience using OpenTrans.net or VSCode under Linux so I quickly googled for this error. 
Is it possible that the project isn't open? At least these two postings suggest this:

https://stackoverflow.com/questions/57908712/error-on-adding-nuget-package-from-vs-code
https://github.com/microsoft/vscode-maven/issues/277

**Comment by stephanstapel** [comment]
I also found that the package was .net 4.6.2 which will not work under Linux. So I updated it into .net standard 2.0. Waiting for your feedback.

**Comment by zdavatz** [comment]
I still get the same error. Can you install your Nuget-Package in Visual Code on Windows?

![latest-screenshot](https://user-images.githubusercontent.com/4953/82637064-4cc4f580-9c04-11ea-9d27-ef8aa879ace9.png)

**Comment by zdavatz** [comment]
I really would like to test this software in Visual Code on Linux. If your Plugin runs in Visual Code on Windows, it will work on Linux as well. ;)

**Comment by stephanstapel** [comment]
I updated the package to version 1.3.0 since I forgot to modify the package to net standard 2.0 accordingly. Please try again. It works fine now with net core 3.1 in VSCode.

**Comment by zdavatz** [comment]
I just tried again, and I still get

![latest-screenshot](https://user-images.githubusercontent.com/4953/82726325-9fc1aa00-9ce3-11ea-9e87-c80d660e1be3.png)

**Comment by zdavatz** [comment]
Ok, I just installed `https://dot.net/v1/dotnet-install.sh` on Linux. 

Adding this as well to my `.bashrc`
```
export ASPNETCORE_ENVIRONMENT=/home/zeno/.dotnet/
export PATH="$HOME/.dotnet/:$PATH"
```
still getting the same error. 

```
~> dotnet --list-sdks
3.1.300 [/home/zeno/.dotnet/sdk]
```

**Comment by stephanstapel** [comment]
This is really odd, sorry for this.
As written above, I set up a small .net core project using VSCode. Maybe the .csproj file helps? It looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>opentrans_vscode_test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="opentrans.net" Version="1.3.0" />
  </ItemGroup>
</Project>
```

with the program itself basically as:
```cs
static void Main(string[] args)
{            
  Order order = new Order()
  {
    Id = "OID1",
    OrderDate = new DateTime(2009, 05, 13, 6, 20, 0),
    DesiredDeliveryDateStart = new DateTime(2009, 05, 20, 10, 0, 0),
    DesiredDeliveryDateEnd = new DateTime(2009, 05, 20, 10, 0, 0),
  };
}
```

**Comment by zdavatz** [comment]
I would like to test your software on Linux an convert and EDIFACT D.96A order file to Opentrans 2.1. Does your software support that yet?

**Comment by stephanstapel** [comment]
The functionality of the library is to read and write OpenTrans information.
Along the process chain, you can use the sister library BMECAT.net for catalog information and OpenTrans.net for Order and OrderResponse.

A demo outlining the functionality is here:

https://github.com/stephanstapel/OpenTrans.net/blob/master/OpenTrans.net-Test/Application.cs

**Comment by zdavatz** [comment]
Yes thank you, I read that. But what about transformation from and to EDIFACT D.96.A files?

**Comment by stephanstapel** [comment]
This library isn't about EDIFACT but only OpenTrans.

**Comment by zdavatz** [comment]
Ok. Thank you!
